# Practical session 3 - Practice with numpy

Course: [SDIA-Python](https://github.com/guilgautier/sdia-python)

Date: 10/06/2021

Instructor: [Guillaume Gautier](https://guilgautier.github.io/)

Students (pair):
- [Student 1]([link](https://github.com/username1))
- [Student 2]([link](https://github.com/username2))

In [2]:
%load_ext autoreload
%autoreload 2

import numpy as np
from sdia_python.lab2.utils import get_random_number_generator

In [2]:
my_array = np.array([0])
print(type(my_array))
dir(np.ndarray)

<class 'numpy.ndarray'>


['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__

Propose at leat 2 ways to create an integer vector of size 100 made of 1s

In [6]:
vector1=np.ones(100)
vector2=np.zeros(100)+1
print(vector1)
print(vector2)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1.]


Create a vector with values ranging from 10 to 49

In [8]:
vec=np.arange(10,50)
vec

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

Propose a way to construct the vector $(0.0, 0.2, 0.4, 0.6, 0.8)$

In [19]:
vect1=np.array([0, 0.2, 0.4, 0.6, 0.8])
vect2=np.arange(0, 1, 0.2)
print(vect1)
print(vect2)

[0.  0.2 0.4 0.6 0.8]
[0.  0.2 0.4 0.6 0.8]


Convert a float array into an integer array in place

In [60]:
floatvec=np.array([1.2, 5.2, 2.0])
floatvec.astype(int)

TypeError: 'numpy.ndarray' object is not callable

Given a boolean array

- return the indices where True
- negate the array inplace? 

In [55]:
bl=np.array([True,False,True,True,False])


In [56]:
np.where(bl==True)


(array([0, 2, 3], dtype=int64),)

In [57]:
np.invert(bl)

array([False,  True, False, False,  True])

Given 2 vectors $u, v$, propose at least

- 2 ways to compute the inner product $v^{\top} u$ (here they must have the same size)
- 2 ways to compute the outer product matrix $u v^{\top}$
- 2 ways to compute the outer sum matrix "$M = u + v^{\top}$", where $M_{ij} = u_i + v_j$

In [11]:
u=np.array([1, 2, 3])
v=np.array([0, 1, 2])
ide=np.ones(3)

In [4]:
np.dot(u,v)

8

In [5]:
np.sum(u*v)

8

In [7]:
np.outer(u,v)

array([[0, 1, 2],
       [0, 2, 4],
       [0, 3, 6]])

In [9]:
uu=np.matrix(u)
vv=np.matrix(v)
np.array(uu.T*vv)

array([[0, 1, 2],
       [0, 2, 4],
       [0, 3, 6]])

In [13]:
np.outer(u,ide)+np.outer(v,ide).T

array([[1., 2., 3.],
       [2., 3., 4.],
       [3., 4., 5.]])

In [22]:
np.array(np.matrix([u,u,u]).T+np.matrix([v,v,v]))

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]])

Given the following matrix

$$
M = 
\begin{pmatrix}
    0 & 1 & 2 \\
    3 & 4 & 5 \\
    6 & 7 & 8 \\
\end{pmatrix}
$$

- Create $M$ using as a list of lists and access the element in the middle
- Propose at least 2 ways to create $M$ using numpy and access the element in the middle
- Swap its first and second row
- Propose at least 3 ways to extract the submatrix $\begin{pmatrix}4 & 5 \\7 & 8 \\\end{pmatrix}$
- Propose at least 2 ways to extract the diagonal of $M$
- Propose at least 2 ways to compute $M^3$
- Compute $v^{\top} M$, resp. $M N$ for a vector, resp. a matrix of your choice. 
- Propose 2 ways to "vectorize" the matrix, i.e., transform it into
  - $(0, 1, 2, 3, 4, 5, 6, 7, 8)$
  - $(0, 3, 6, 1, 4, 7, 2, 5, 8)$
- Consider $v = (1, 2 , 3)$, compute the
  - row-wise multiplication of $M$ by $v$ ($M_{i\cdot}$ is multiplied by $v_i$)
  - column-wise multiplication of $M$ by $v$ ($M_{\cdot j}$ is multiplied by $v_i$)

In [82]:
M = [[0, 1, 2],
    [3, 4, 5],
    [6, 7, 8]]

M[1][1]

4

In [83]:
M1 = np.array(M)
M1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [3]:
M2 = np.arange(0,9).reshape(3,3)
M2

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [87]:
M1[0, :] = M1[1, :]
M1[1, :] = M2[0, :]
M1

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

In [88]:
M2[1:, 1:]

array([[4, 5],
       [7, 8]])

In [89]:
M2[np.ix_([1,2],[1,2])]

array([[4, 5],
       [7, 8]])

In [90]:
np.diag(M2)

array([0, 4, 8])

In [93]:
M2.diagonal()

array([0, 4, 8])

In [99]:
np.dot(np.dot(M2, M2), M2)

array([[ 180,  234,  288],
       [ 558,  720,  882],
       [ 936, 1206, 1476]])

In [98]:
Mmatrix=np.matrix(M2)
np.array(Mmatrix**3)

array([[ 180,  234,  288],
       [ 558,  720,  882],
       [ 936, 1206, 1476]])

In [103]:
v=np.array([1, 0, 1])
N=np.array([[1, 0, 0],
           [0, 1, 0], 
           [0, 0, 1]])
print(np.dot(v, M2))
print(np.dot(M2, N))

[ 6  8 10]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [124]:
M2.reshape(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [135]:
np.resize(M2,9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [130]:
M2.T.reshape(9)

array([0, 3, 6, 1, 4, 7, 2, 5, 8])

In [136]:
np.resize(M2.T,9)

array([0, 3, 6, 1, 4, 7, 2, 5, 8])

In [144]:
v=np.array([1, 2, 3])

In [145]:
(M2.T*v).T

array([[ 0,  1,  2],
       [ 6,  8, 10],
       [18, 21, 24]])

In [146]:
M2*v

array([[ 0,  2,  6],
       [ 3,  8, 15],
       [ 6, 14, 24]])

Write a function `is_symmetric` that checks whether a given n x n matrix is symmetric, and provide an example

In [15]:
def is_symmetric(M):
    l=M==M.T
    return not (False in l)

In [19]:
A=np.array([[1,2,3],[2,5,6],[3,6,7]])

In [20]:
is_symmetric(A)

True

In [21]:
is_symmetric(M2)

False

## Random

REQUIREMENT: USE THE FUNCTION `get_random_number_generator` as previously used in Lab 2.

Consider the Bernoulli(0.4) distribution

- Propose at least 2 ways to generate n=1000 samples from it
- Compute the empirical mean and variance

In [26]:
rng = get_random_number_generator(None)

In [40]:
ber=rng.binomial(1, 0.4, 1000)
ber

array([0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0,
       0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1,
       0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0,

In [39]:
l=np.zeros(1000)
for i in range(1000):
    l[i]=rng.binomial(1, 0.4)
l

array([0., 0., 0., 1., 0., 0., 1., 0., 1., 0., 1., 0., 0., 1., 1., 0., 0.,
       0., 0., 1., 0., 1., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1.,
       1., 0., 0., 0., 0., 1., 0., 0., 1., 0., 0., 1., 1., 1., 0., 1., 1.,
       0., 0., 1., 1., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 0., 0., 0.,
       0., 1., 0., 0., 1., 1., 0., 1., 0., 1., 1., 1., 0., 0., 1., 0., 1.,
       0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 1., 1.,
       0., 0., 0., 1., 1., 0., 0., 1., 0., 0., 1., 1., 0., 0., 1., 1., 1.,
       0., 0., 1., 1., 1., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 1., 1.,
       0., 0., 0., 1., 1., 0., 0., 1., 1., 0., 1., 0., 1., 0., 1., 0., 1.,
       1., 1., 0., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 0., 0., 0., 1.,
       1., 1., 0., 1., 1., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
       1., 0., 1., 1., 0., 0., 0., 0., 1., 0., 1., 1., 0., 1., 0., 0., 1.,
       0., 0., 1., 1., 0., 0., 0., 1., 1., 1., 0., 1., 0., 1., 0., 0., 1.,
       1., 1., 0., 0., 0.

In [41]:
ber.mean()

0.419

In [42]:
ber.std()

0.493395378981198

Consider a random matrix of size $50 \times 100$, filled with i.i.d. standard Gaussian variables, compute

- the absolute value of each entry
- the sum of each row
- the sum of each colomn 
- the (euclidean) norm of each row
- the (euclidean) norm of each column